name: Create Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: |
            Automated release from master on run ${{ github.run_number }}
          draft: false
          prerelease: false
